version: '3'

services:
  restaurants-api:
    build: ./restaurants-api
    ports:
      - "8081:8081"
    networks:
      - app-network
      - api-db-network
    depends_on:
      - api-db

  web-app:
    build: ./web-app
    ports:
      - "8082:8082"
    networks:
      - app-network
      - app-db-network
    depends_on:
      - app-db
      - restaurants-api

  api-db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - api-db-network
    environment:
      POSTGRES_USER: 'apiuser'
      POSTGRES_PASSWORD: 'apipassword'
      POSTGRES_DB: 'api-database'

  app-db:
    image: postgres
    ports:
      - "5433:5433"
    networks:
      - app-db-network
    environment:
      POSTGRES_USER: 'appuser'
      POSTGRES_PASSWORD: 'apppassword'
      POSTGRES_DB: 'app-database'
      PGPORT: 5433

networks:
  app-network:
  api-db-network:
  app-db-network:
