server:
  port: 8082
  servlet:
    context-path: /web-app

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://app-db:5433/app-database
    username: appuser
    password: apppassword
    hikari:
      idle-timeout: 10000
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      format-sql: true
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
      springframework:
        security: DEBUG
